#!/bin/bash
PROJECT=vest_firmware

HEX=${PROJECT}.hex
DEV=$(ls /dev/ | grep ttyUSB)
avr-objcopy -O ihex -R .eeprom $PROJECT $HEX
SIZE=$(avr-size $HEX | grep $HEX | awk '{print $2}' )
SIZE_KB=$(python -c "print $SIZE/1024")
echo $SIZE_KB/32 KB
read -p "Are you sure? " -n 1 -r
echo  
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
avrdude -V -c arduino -p atmega328p -b 57600 -P /dev/${DEV} -Uflash:w:${HEX}:i -D

